### ISSUE TITLE
Add functionality for LOC endpoint

### ISSUE THREAD

**Issue by LakshyaKhatri** [MLH-Fellowship/Fellowship-Companion#23]
An implementation for getting lines of code `/api/v1/loc/`

**Comment by AlbertoPdRF** [comment]
As discussed on Discord, instead of a `loc` endpoint we could have a `home` or whatever one which returns all the information required by the front end's homepage (see #25). This should be, at least:

```json
{
  "loc": "1234567890",
  "fellows": "100",
  "projects": "50",
}
```

And I would personally like to fetch and display `contributions` instead of `loc`, what do you think?
